services:
  - type: worker
    name: ted-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8395744940:AAGmZVdj1l-QfZ4zqGP_9XOOvO9EbsnyWLw
      - key: TELEGRAM_CHAT_ID
        value: 2133274440
      - key: TED_API_KEY
        value: 0f0d8c2f68bb46bab7afa51c46053433
